<?php

namespace app\models;


use yii\db\ActiveRecord;

class Newtable extends ActiveRecord
{
    public static function tableName()
    {
        return "newtable"; // TODO: Change the autogenerated stub
    }
}